# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraints/lab1_constraints.xdc

# Block Designs: bd/arm/arm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm || ORIG_REF_NAME==arm} -quiet] -quiet

# IP: bd/arm/ip/arm_processing_system7_0_0/arm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_processing_system7_0_0 || ORIG_REF_NAME==arm_processing_system7_0_0} -quiet] -quiet

# IP: bd/arm/ip/arm_axi_gpio_0_0/arm_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_axi_gpio_0_0 || ORIG_REF_NAME==arm_axi_gpio_0_0} -quiet] -quiet

# IP: bd/arm/ip/arm_xbar_0/arm_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_xbar_0 || ORIG_REF_NAME==arm_xbar_0} -quiet] -quiet

# IP: bd/arm/ip/arm_ps7_0_axi_periph_0/arm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_ps7_0_axi_periph_0 || ORIG_REF_NAME==arm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/arm/ip/arm_rst_ps7_0_100M_0/arm_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_rst_ps7_0_100M_0 || ORIG_REF_NAME==arm_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_axi_gpio_0_1 || ORIG_REF_NAME==arm_axi_gpio_0_1} -quiet] -quiet

# IP: bd/arm/ip/arm_auto_pc_0/arm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_auto_pc_0 || ORIG_REF_NAME==arm_auto_pc_0} -quiet] -quiet

# IP: bd/arm/ip/arm_gray_counter_ip_0_0/arm_gray_counter_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_gray_counter_ip_0_0 || ORIG_REF_NAME==arm_gray_counter_ip_0_0} -quiet] -quiet

# XDC: bd/arm/arm_ooc.xdc
