# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_xbar_0/arm_xbar_0.xci
# IP: The module: 'arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_xbar_0/arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_xbar_0/arm_xbar_0.xci
# IP: The module: 'arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_xbar_0/arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
