# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1.xci
# IP: The module: 'arm_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1.xci
# IP: The module: 'arm_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/jesterhead1924/Documents/embedded_systems/Labs/vivado-projects/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_axi_gpio_0_1/arm_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
